const aptPackages = [
  "ca-certificates",
  "curl",
  "chromium",
  "git",
  "python3",
  "python3-pip",
  "unzip",
  "xdg-utils",
  "libnss3",
  "libgbm1",
  "libxss1",
  "libxshmfence1",
  "libatk1.0-0",
  "libatk-bridge2.0-0",
  "libcups2",
  "libdrm2",
  "libxkbcommon0",
  "libxcomposite1",
  "libxdamage1",
  "libxfixes3",
  "libxrandr2",
  "libpango-1.0-0",
  "libcairo2",
  "libasound2",
  "fonts-liberation",
  "fonts-freefont-ttf",
  "libfreetype6",
  "libharfbuzz0b",
];

export default {
  name: "browser-agent",
  base: "node:20-bookworm",
  env: {
    DEBIAN_FRONTEND: "noninteractive",
    HOME: "/root",
    XDG_CONFIG_HOME: "/root/.config",
    CODEX_HOME: "/root/.codex",
    CHROME_BIN: "/usr/bin/chromium",
    PUPPETEER_EXECUTABLE_PATH: "/usr/bin/chromium",
    PUPPETEER_SKIP_DOWNLOAD: "true",
    AGENT_BROWSER_EXECUTABLE_PATH: "/usr/bin/chromium",
    AGENT_BROWSER_ARGS: "--no-sandbox",
  },
  run: [
    `apt-get update && apt-get install -y --no-install-recommends ${aptPackages.join(" ")} && rm -rf /var/lib/apt/lists/*`,
    "npm cache clean --force",
    "npm install -g pnpm @anthropic-ai/claude-code @openai/codex opencode-ai agent-browser",
    "agent-browser set viewport 1980 1080",
  ],
  workdir: "/workspace",
  cmd: ["sleep", "infinity"],
  resources: {
    cpu: 4,
    memoryMiB: 8192,
  },
};
